Limdo.Web.App/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Limdo.Web.App.Controllers
{
    public class AuthenticationController : Controller
    {
        [HttpGet]
        public IActionResult AccessDenied()
        {
            return View();
        }

        [HttpGet]
        public async Task Logout()
        {
            await HttpContext.SignOutAsync();
            await HttpContext.SignOutAsync("oidc");
        }
    }
}

Limdo.Web.App/Controllers/PcoLicencesDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Limdo.Web.App.ApiClients;
using Limdo.Web.App.DtoModels;
using Limdo.Web.App.HttpService;
using Limdo.Web.App.Models;
using Limdo.Web.App.Security;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Limdo.Web.App.Controllers
{
    public class PcoLicencesDetailsController : Controller
    {

        private const string BaseUri = "PcoLicenceDetails/GetPcoDetails";
        private const string Pdl_ByAppUserId = "PcoLicenceDetails/GetPcoLicenceDetailByAppUserId";
        private const string BaseUri_AppUser = "AppUsers";
        private const string Pdl_PostPdl = "PcoLicenceDetails";
        private const string BaseUri_AppUserById = "AppUsers/GetByAppUserId";
        private const string AppUserBaseUri = "AppUsers";

        private readonly IApiClient _apiClient;
        private readonly IMapper _mapper;


        public PcoLicencesDetailsController(IApiClient apiClient, IMapper mapper)
        {
            _apiClient = apiClient;
            _mapper = mapper;
        }


        [HttpGet]
        // GET: PcoLicencesDetails
        public async Task<ActionResult> Index()
        {
            var path = string.Format("{0}",  BaseUri);
            var pcoLicenceDetails = _mapper.Map<IEnumerable<PcoLicenceDetailViewModel>>(await _apiClient.ListAsync<PcoLicenceDetailDto>(path));
            pcoLicenceDetails = await PopulateUriKeysAsync(pcoLicenceDetails.ToList());
            return View(pcoLicenceDetails);
        }


        [HttpGet]
        // GET: PcoLicencesDetails/Details/5
        public async Task<ActionResult> Details(string id)
        {
            var decodedId = GuidEncoder.Decode(id).ToString();

            var path = string.Format("{0}/{1}", BaseUri, decodedId);
            var pcoLicence = _mapper.Map<PcoLicenceDetailViewModel>(await _apiClient.GetAsync<PcoLicenceDetailDto>(path));
            return View(pcoLicence);
        }


        [HttpGet]
        // GET: PcoLicencesDetails/Create
        public async Task<ActionResult> Create(string id)
        {


            var decodedId = GuidEncoder.Decode(id).ToString();
            var path = string.Format("{0}/{1}", Pdl_ByAppUserId, decodedId);
            var pld = _mapper.Map<PcoLicenceDetailViewModel>(await _apiClient.GetAsync<PcoLicenceDetailDto>(path));
            if (pld == null)
            {
                var newPdl = new PcoLicenceDetailViewModel()
                {
                    AppUserUriKey = id
                };
                return View(newPdl);
            }
            else
            {
                return View();
            }


            
        }




        // POST: PcoLicencesDetails/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PcoLicenceDetailViewModel model)
        {

            

            try
            {
                if (ModelState.IsValid)
                {
                    var decodedId = GuidEncoder.Decode(model.AppUserUriKey).ToString();
                    var path = string.Format("{0}/{1}", BaseUri_AppUserById, decodedId);
                    var appUser = _mapper.Map<AppUserViewModel>(await _apiClient.GetAsync<AppUserDto>(path));


                    //var updateAppUserPath = string.Format("{0}", BaseUri_AppUser);
                    //model.AppUserId = string.Empty;
                    //model.AppUserId = appUser.AppUserId;
                    //appUser.PcoLicenceDetail = model;
                    //await _apiClient.PutAsync<AppUserDto>(updateAppUserPath, _mapper.Map<AppUserDto>(appUser));



                    //var createPath = string.Format("{0}",Pdl_PostPdl);
                    //model.AppUserId = appUser.AppUserId;
                    //await _apiClient.PostAsync<PcoLicenceDetailDto>(createPath, _mapper.Map<PcoLicenceDetailDto>(model));
                    var createPath = string.Format("{0}{1}", HttpClientProvider.HttpClient.BaseAddress, Pdl_PostPdl);
                    //model.AppUser = appUser;
                    model.AppUserId = appUser.AppUserId;
                    await _apiClient.PostAsync<PcoLicenceDetailDto>(createPath, _mapper.Map<PcoLicenceDetailDto>(model));
                    return RedirectToAction(nameof(Index));
                }
                // TODO: Add insert logic here

                return View();
            }
            catch(Exception ex)
            {
                var errMsg = ex.Message;
                return View();
            }
        }

        // GET: PcoLicencesDetails/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var decodedId = GuidEncoder.Decode(id).ToString();
            var path = string.Format("{0}/{1}", BaseUri, decodedId);
            var pdl = _mapper.Map<PcoLicenceDetailViewModel>(await _apiClient.GetAsync<PcoLicenceDetailDto>(path));
            pdl.UriKey = GuidEncoder.Encode(pdl.AppUserId);
            return View(pdl);
        }

        // POST: PcoLicencesDetails/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(PcoLicenceDetailViewModel model)
        {
            var path = string.Format("{0}/{1}", BaseUri, model.UriKey);
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    await _apiClient.PutAsync<PcoLicenceDetailDto>(_mapper.Map<PcoLicenceDetailDto>(model));
                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            catch(Exception ex)
            {
                var errMsg = ex.Message;
                return View();
            }
        }

        // GET: PcoLicencesDetails/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PcoLicencesDetails/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<IEnumerable<PcoLicenceDetailViewModel>> PopulateUriKeysAsync(List<PcoLicenceDetailViewModel> pcoLicenceDetails)
        {
            return await Task.Run(() =>
                
                pcoLicenceDetails.Select(pld => 
                {
                    pld.UriKey = GuidEncoder.Encode(pld.AppUserId); return pld; 
                })
            );
        }



    }
}

Limdo.Web.App/Controllers/RegistrationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Limdo.Data.Security.Helpers;
using Limdo.Web.App.ApiClients;
using Limdo.Web.App.DtoModels;
using Limdo.Web.App.HttpService;
using Limdo.Web.App.Models;
using Limdo.Web.App.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Limdo.Web.App.Controllers
{
    public class RegistrationsController : Controller
    {
        private const string Registration_BaseUri = "Users";
        private const string Registration_EmailUri = "Users/GetUserBymail";
        private const string User_ByUserIdUri = "Users/GetByUserId";
        private const string Registration_UserUri = "Users/GetUser";

        private const string Genders_Uri = "DropDownLists/GetGenders";
        private const string DDL_Uri = "DropDownLists";
        private const string Countries_Uri = "DropDownLists/GetCountries";

        private const string Base_AppUserUri = "AppUsers";
        private const string AppUsers_Post = "AppUsers/PostAppUser";
        private const string Base_GetAppUserUri = "AppUsers/GetByAppUserId";
        private const string AppUsers_Put = "AppUsers/PutAppUser";

        private readonly IMapper _mapper;
        private readonly IApiClient _apiClient;

        public RegistrationsController(IMapper mapper, IApiClient apiClient)
        {
            _apiClient = apiClient;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Registration()
        {
            var newUser = new RegistratioViewModel();
            return View(newUser);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Registration(RegistratioViewModel model)
        {
            model.Username = model.Email;
            var path = string.Format("{0}{1}", HttpClientProvider.HttpClient.BaseAddress, Registration_BaseUri);

            if (ModelState.IsValid)
            {
                model.Password = PasswordBaseKeyDerivationFunction.HashPassword(model.Password);
                model.IsActive = true;
                var result = _mapper.Map<UserDto>(await _apiClient.PostAsync(path, model));

                return RedirectToAction("WelcomeNewUser", "CustomerRelationshipMgms", new { emailId = model.Email });

            }


            return View();
        }

        // GET: CustomerRelationshipMgms/Details/5
        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Details(string id)
        {

            var path = string.Format("{0}/{1}", Registration_EmailUri, GuidEncoder.Decode(id).ToString()) ;
            var user = await _apiClient.GetAsync<UserDto>(path);
            var appUserPath = string.Format("{0}/{1}", Base_GetAppUserUri, GuidEncoder.Decode(id).ToString());
            var appUser = _mapper.Map<AppUserViewModel>(await _apiClient.GetAsync<AppUserDto>(appUserPath));
            appUser = await PopulateCountryGenderIdsValuesAsync(appUser);


            return View(appUser);
        }

        [HttpGet]
        public async Task<ActionResult> Create(string id)
        {
            var path = string.Format("{0}/{1}", Registration_EmailUri, id);
            var user = await _apiClient.GetAsync<UserDto>(path);

            var newUser = new AppUserViewModel();
            newUser.UriKey = GuidEncoder.Encode(user.SubjectId);
            return View(newUser);
        }


        [Authorize]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<ActionResult> Create(AppUserViewModel model)
        {
            var path = string.Format("{0}/{1}", Registration_BaseUri, model);
            var user = await _apiClient.PostAsync<UserDto>(path, _mapper.Map<UserDto>(model));

            var newUser = new AppUserViewModel();
            newUser.UriKey = GuidEncoder.Encode(user.SubjectId);
            return View(newUser);
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Edit(string id)
        {
            await PopulateViewBagsAsync();
            
            var path = string.Format("{0}/{1}", Registration_BaseUri, id);
            var user = await _apiClient.GetAsync<UserDto>(path);

            var newUser = new AppUserViewModel();
            newUser.UriKey = GuidEncoder.Encode(user.SubjectId);
            newUser.DisplayName = id;
            return View(newUser);
        }

        // POST: CustomerRelationshipMgms/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AppUserViewModel model)
        {

            var userPath = string.Format("{0}/{1}", User_ByUserIdUri, GuidEncoder.Decode(model.UriKey));
            var user = _mapper.Map<UserViewModel>(await _apiClient.GetAsync<UserDto>(userPath));



            try
            {
                var redirectUrlParam = model.UriKey;
                var path = string.Format("{0}{1}", HttpClientProvider.HttpClient.BaseAddress, Base_AppUserUri);
                //model.SubjectId = GuidEncoder.Decode(model.UriKey).ToString();
                model.CreatedDate = DateTime.UtcNow;
                model.ModifiedDate = DateTime.UtcNow;
                model.GenderId = GuidEncoder.Decode(model.GenderId).ToString();
                model.CountryId = GuidEncoder.Decode(model.CountryId).ToString();

                if (ModelState.IsValid)
                {
                    model.User = user;
                    await _apiClient.PostAsync(path, _mapper.Map<AppUserDto>(model));
                    return RedirectToAction("Details", new {emailId = redirectUrlParam});
                }
                // TODO: Add update logic here

                return View();
            }
            catch(Exception ex)
            {
                var msgError = ex.Message;
                return View();
            }
        }


        private async Task<AppUserViewModel> PopulateCountryGenderIdsValuesAsync(AppUserViewModel appUser)
        {
            var countries = await GetCountriesAsync();
            var genders = await GetGendersAsync();
            appUser = await Task.Run(() => GetCountryIdValue(countries, appUser));
            appUser = await Task.Run(() => GetGenderIdValue(genders, appUser));
            return appUser;
        }

        private AppUserViewModel GetCountryIdValue(IEnumerable<CountryViewModel> genders, AppUserViewModel appUser)
        {
            appUser.CountryIdValue = genders.FirstOrDefault(g => string.Compare(g.CountryId, appUser.CountryId, true) == 0).CountryName;
            return appUser;
        }

        private AppUserViewModel GetGenderIdValue(IEnumerable<GenderViewModel> genders, AppUserViewModel appUser)
        {
            appUser.GenderIdValue = genders.FirstOrDefault(g => string.Compare(g.GenderId, appUser.GenderId, true) == 0).Type;
            return appUser;
        }



        private async Task<IEnumerable<CountryViewModel>> GetCountriesAsync()
        {
            var path = string.Format("{0}", Countries_Uri);
            return _mapper.Map<IEnumerable<CountryViewModel>>(await _apiClient.ListAsync<CountryDto>(path));
        }

        private async Task<CountryViewModel> GetCountryAsync(string countryId)
        {
            //var path = string.Format("{0}", Countries_Uri);
            var path = string.Format("{0}", Countries_Uri);
            return _mapper.Map<CountryViewModel>(await _apiClient.ListAsync<CountryDto>(path));
        }

        private async Task<IEnumerable<GenderViewModel>> GetGendersAsync()
        {
            //var path = string.Format("{0}", Genders_Uri);
            var path = string.Format("{0}", Genders_Uri);
            return _mapper.Map<IEnumerable<GenderViewModel>>(await _apiClient.ListAsync<GenderDto>(path));
        }

        private async Task<GenderViewModel> GetGenderAsync(string genderId)
        {
            var path = string.Format("{0}/{1}", Countries_Uri, genderId);
            return _mapper.Map<GenderViewModel>(await _apiClient.GetAsync<GenderDto>(path));
        }

        public async Task<IEnumerable<GenderViewModel>> PopulateGenderUriKeyAsync(List<GenderViewModel> genders)
        {
            return await Task.Run(() => 

                genders.Select(g => { g.UriKey = GuidEncoder.Encode(g.GenderId); return g; })
            );
        }

        public async Task<IEnumerable<CountryViewModel>> PopulateCountryUriKeyAsync(List<CountryViewModel> countries)
        {
            return await Task.Run(() =>

                countries.Select(g => { g.UriKey = GuidEncoder.Encode(g.CountryId); return g; })
            );
        }

        public async Task PopulateViewBagsAsync()
        {
            var genders = await GetGendersAsync();
            var countries = await GetCountriesAsync();
            genders = await PopulateGenderUriKeyAsync(genders.ToList());
            countries = await PopulateCountryUriKeyAsync(countries.ToList());
            ViewBag.Genders = genders;
            ViewBag.Countries = countries;
        }
    }
}

Limdo.Web.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Limdo.Web.App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/customCss.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Limdo.Web.App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CustomerRelationshipMgms" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PcoLicencesDetails" asp-action="Index">Licences Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registrations" asp-action="Registration">Registration</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registrations" asp-action="Registration">Login</a>
                        </li>*@

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Logout</a>
                            </li>

                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Limdo.Web.App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Limdo.Web.App/Views/Shared/_LayoutAbout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Limdo.Web.App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/customCss.css" rel="stylesheet" />
</head>
<body class="aboutPage img-responsive">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Limdo.Web.App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CustomerRelationshipMgms" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PcoLicencesDetails" asp-action="Index">Licences Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registrations" asp-action="Registration">Registration</a>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Registrations" asp-action="Registration">Login</a>
                            </li>*@

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Logout</a>
                            </li>

                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Limdo.Web.App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Limdo.Web.App/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Limdo.Web.App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/customCss.css" rel="stylesheet" />
</head>
<body class="homePage img-responsive">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Limdo.Web.App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CustomerRelationshipMgms" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PcoLicencesDetails" asp-action="Index">Licences Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registrations" asp-action="Registration">Registration</a>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Registrations" asp-action="Registration">Login</a>
                            </li>*@

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Logout</a>
                            </li>

                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Limdo.Web.App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Limdo.Web.App/Views/Shared/_LayoutWelcome.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Limdo.Web.App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/customCss.css" rel="stylesheet" />
</head>
<body class="aboutPage img-responsive">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Limdo.Web.App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CustomerRelationshipMgms" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PcoLicencesDetails" asp-action="Index">Licences Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registrations" asp-action="Registration">Registration</a>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Registrations" asp-action="Registration">Login</a>
                            </li>*@

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Logout</a>
                            </li>

                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Limdo.Web.App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>